# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./qt_realtimeio_app.h

#Source files
SOURCES += ./main.cpp \
    ./qt_realtimeio_app.cpp

#Forms
FORMS += ./qt_realtimeio_app.ui

#Resource file(s)
#this is not used yet, disable
#RESOURCES += .\qt_realtimeio_app.qrc
